### ISSUE TITLE
Add developers to Heroku app

### ISSUE THREAD

**Issue by stravid** [DominikGuzei/cmb-prototypes-website#1]
All developers should be allowed to deploy

david.strausz@gmail.com

**Comment by stravid** [comment]
@MathiasPaumgarten @egraether @bmedicke @Joe-Z Please add your Heroku email adress!

**Comment by roboshoes** [comment]
mail@mathias-paumgarten.com

**Comment by roboshoes** [comment]
Sorry - wrong button ...

**Comment by DominikGuzei** [comment]
Added Thomas, David and Mathias to heroku app!
